version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: always
    networks:
      - service_network
    volumes:
      - ./data/:/data/
      - ./ssl/:/ssl/
    env_file:
      - ../.env
    environment:
      - ADMIN_TOKEN=BITWARDEN_ADMIN_TOKEN
      - SIGNUPS_ALLOWED=false
networks:
  service_network:
    external: true
