version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    networks: 
      - service_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/:/etc/nginx/conf.d/
      - ./certs/:/etc/nginx/certs:ro

networks:
  service_network:
    external: true

