version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - service_network
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  service_network:
    external: true
